management:
  security:
    enabled: false
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
        base-path: /actuator
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'

server:
  port: 5001

spring:
  application:
    name: authservice

  cloud:
    discovery:
      service-id: authservice
      enabled: true

  zipkin:
    baseUrl: ${ZIPKIN_URI:http://127.0.0.1:9411}
    enabled: true
  sleuth:
    enabled: true
    http:
      enabled: true
    sampler:
    percentage: 1

  data:
    mongodb:
      #       uri: mongodb://BingoBongo:Abcdf@127.0.0.1:27017/userDB?ssl=false&connectTimeoutMS=300000&minPoolSize=0&maxPoolSize=100&maxIdleTimeMS=900000&authSource=admin
      uri: mongodb://127.0.0.1:27017/payment?ssl=false&connectTimeoutMS=300000&minPoolSize=0&maxPoolSize=100&maxIdleTimeMS=900000&authSource=admin



jwt:
  header: Authorization
  expires_in: 300000
  mobile_expires_in: 400000
  secret: supersecret2019
  zuulSecret: zuulSecret2025

eureka:
  instance:
    hostname: authservice
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    leaseExpirationDurationInSeconds: 3
  client:
    hostname: authservice
    enabled: true
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true
    lease:
      duration: 5
    serviceUrl:
      #      defaultZone: ${EUREKA_URI:http://mpOwner:mp19181975Secret@127.0.0.1:8761/eureka}
      defaultZone: http://127.0.0.1:8761/eureka
